"""Parity pin for the price-action pattern library (engulfing, liquidity_sweep,
pivot_structure) on the shared BTCUSDT 1h x300 reference fixture.

Values generated by the Python engine (SignalService with the canonical
default.yaml — thresholds equal to the in-code defaults, so the Android
empty-config path produces the same numbers). The Kotlin side pins the same
signal+score in ExtendedIndicatorsFixtureTest.
"""

import json
import pathlib

import pandas as pd
import pytest

from diveintocrypto_desktop.engine.loader import load_config
from diveintocrypto_desktop.engine.signal_service import SignalService

FX = pathlib.Path(__file__).parent / "fixtures"

# Final-bar outputs pinned 2026-09-12 from the Python reference engine.
EXPECTED = {
    "engulfing": {
        "signal": "NEUTRAL",
        "score": 0,
        "raw": {"body_cur": 7.48, "body_prev": 302.82, "body_ratio": 0.0476},
    },
    "liquidity_sweep": {
        "signal": "NEUTRAL",
        "score": 0,
        "raw": {
            "swing_low": 76719.47,
            "swing_high": 78098.16,
            "atr": 440.305,
        },
    },
    "pivot_structure": {
        "signal": "SELL",
        "score": -1,
        "raw": {
            "last_swing_high": 78098.16,
            "prev_swing_high": 78200.0,
            "last_swing_low": 76719.47,
            "prev_swing_low": 77521.0,
        },
    },
}


def _dataframe() -> pd.DataFrame:
    candles = json.loads((FX / "btcusdt_1h_300.json").read_text())
    return pd.DataFrame(
        [{"open": c["o"], "high": c["h"], "low": c["l"], "close": c["c"], "volume": c["v"]} for c in candles]
    )


def _results() -> dict:
    return {r.name: r for r in SignalService(load_config()).calculate_all(_dataframe())}


@pytest.mark.parametrize("name", sorted(EXPECTED.keys()))
def test_pattern_signal_and_score_exact(name):
    exp = EXPECTED[name]
    got = _results()[name]
    assert got.signal.value == exp["signal"], f"{name}: {got.signal.value} != {exp['signal']}"
    assert got.score == exp["score"], f"{name}: {got.score} != {exp['score']}"


@pytest.mark.parametrize("name", sorted(EXPECTED.keys()))
def test_pattern_raw_values_within_tolerance(name):
    exp = EXPECTED[name]
    raw = _results()[name].raw_values or {}
    for k, v in exp["raw"].items():
        assert k in raw, f"{name}: missing raw value {k}"
        tol = max(0.1, abs(v) * 0.005)
        assert abs(float(raw[k]) - float(v)) <= tol, f"{name}.{k}: {raw[k]} != {v} (tol {tol})"
